# Generated by Django 3.0 on 2020-05-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0002_auto_20200513_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
