# Generated by Django 3.0 on 2020-05-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0004_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='original',
            name='elements',
        ),
        migrations.AddField(
            model_name='original',
            name='elements',
            field=models.ManyToManyField(blank=True, to='posted.Elements'),
        ),
    ]
