# Generated by Django 3.0 on 2020-05-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0005_auto_20200514_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='original',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
