# Generated by Django 3.0 on 2020-05-14 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0006_auto_20200514_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='add_element',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AlterField(
            model_name='original',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
