# Generated by Django 3.0 on 2020-05-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0007_auto_20200514_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='add_element',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
