# Generated by Django 3.0 on 2020-05-15 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posted', '0008_auto_20200514_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posted.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='original',
            name='author',
        ),
        migrations.RemoveField(
            model_name='original',
            name='category',
        ),
        migrations.RemoveField(
            model_name='original',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='original',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Elements',
        ),
        migrations.DeleteModel(
            name='Original',
        ),
    ]
