# Generated by Django 3.0.6 on 2020-05-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0006_good'),
        ('posted', '0010_auto_20200515_1332'),
    ]

    operations = [
    ]
