# Generated by Django 3.0.6 on 2020-05-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0011_merge_20200515_1526'),
        ('posted', '0011_merge_20200515_1525'),
    ]

    operations = [
    ]
